### ISSUE TITLE
What made you pull the plug?

### ISSUE THREAD

**Issue by DamonOehlman** [squiggle-lang/squiggle-lang#166]
Just interested as what made you decide to pull the plug on this?  I found myself reading through the reasons you started the project and I was nodding quite a lot.  Just wondering whether one of the other technologies that you had previously been tinkering had made the grade, or whether it's just the overall effort around maintaining an opensource project (it is a lot of work).

Not something you have to share, but I'm personally very interested.

**Comment by wavebeem** [comment]
It is a lot of work, and that is one of the reasons. Also, most compile-to-JS langs end up dying off at some point and presumably being a nuisance to the companies with large codebases in them, as the effort to migrate to JS is not worth it.

In particular, it's really really hard to find a balance between "works well with JS" and "is a nice language", and that was stressing me out a lot. I have a full time job again, and couldn't deal with the obligation to turn this into a polished final product.

Also— I think this is the biggest thing— it's just *another tool* that raises the complexity of the JS ecosystem. I'm currently thinking of ways right now to help push back on the complexity, rather than adding to it.

Thanks for your kind words, and I'm happy to answer any other questions if you have them.

**Comment by DamonOehlman** [comment]
Thanks Brian - that's all I was after, and good luck at your new FT gig.  Look forward to your thoughts on how to push back on the complexity around JS.  Something I completely agree with you on.  With your experience building squiggle they are bound to be valuable :)
